### ISSUE TITLE
Please replace `githubuser` with `YoshikuniJujo`

### ISSUE THREAD

**Issue by alaendle** [YoshikuniJujo/cairo-image#1]
https://github.com/YoshikuniJujo/cairo-image/blob/5962f42d08eb9db0f4717f9d4cd988601167235f/cairo-image.cabal#L14C40-L14C40

Please replace `githubuser` with `YoshikuniJujo` - otherwise the data displayed on hackage is wrong at URLs will result in 404.

**Comment by YoshikuniJujo** [comment]
https://hackage.haskell.org/package/cairo-image-0.1.0.2

Thank you.
